#!/bin/bash

cat <<EOF | java -jar /usr/share/jenkins/jenkins-cli.jar -s $JENKINS_URL create-node $SLAVE_NAME
<slave>
  <name>${SLAVE_NAME}</name>
  <description></description>
  <remoteFS>${AGENT_WORKDIR}</remoteFS>
  <numExecutors>2</numExecutors>
  <mode>NORMAL</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.slaves.JNLPLauncher"/>
  <label>${SLAVE_NAME}</label>
  <nodeProperties/>
</slave>
EOF
